name        : bmon
version     : 3.7
release     : 3
source     :
    - https://github.com/tgraf/bmon/archive/v3.7.tar.gz : 1e595c9936d8dbc85d91ecc00c3b6a4e49d4f6cade7a8bced3b291925894bb16
license     :
    - BSD
    - MIT
summary     : A command line based bandwidth monitor.
builddeps   :
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-3.0)
    - gnome-common
description : |
    A command line based bandwidth monitor.
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
