name        : bmon
version     : 3.8
release     : 5
source     :
    - https://github.com/tgraf/bmon/archive/v3.8.tar.gz : 6bb2bbdd619f279132e54f1fa83fc98c0f75003766f82d6b7cd36c8a46900453
license     :
    - BSD
    - MIT
summary     : A command line based bandwidth monitor.
builddeps   :
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-3.0)
    - gnome-common
description : |
    A command line based bandwidth monitor.
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
