name       : bmon
version    : '4.0'
release    : 12
source     :
    - https://github.com/tgraf/bmon/archive/v4.0.tar.gz : d5e503ff6b116c681ebf4d10e238604dde836dceb9c0008eb92416a96c87ca40
license    :
    - BSD-2-Clause
    - MIT
summary    : A command line based bandwidth monitor.
builddeps  :
    - gnome-common
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-3.0)
component  : network.util
description: |
    A command line based bandwidth monitor.
setup      : |
    %autogen.sh
build      : |
    %make
install    : |
    %make_install
