name       : bmon
version    : 3.9
release    : 8
source     :
    - https://github.com/tgraf/bmon/archive/v3.9.tar.gz : 02120aafb1959285562074490c0a9f7f8648161f9db534cf5792fc16d6e0326c
license    :
    - BSD-2-Clause
    - MIT
summary    : A command line based bandwidth monitor.
builddeps  :
    - gnome-common
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-3.0)
component  : network.util
description: |
    A command line based bandwidth monitor.
setup      : |
    %autogen.sh
build      : |
    %make
install    : |
    %make_install
