name        : bmon
version     : 3.6
release     : 2
source     :
    - https://github.com/tgraf/bmon/archive/v3.6.tar.gz : 7d9d9b5af751cb61e267b43309506f03e82636282742fce89209f2378ae6a4b1
license     :
    - BSD
    - MIT
summary     : A command line based bandwidth monitor.
builddeps   :
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-3.0)
    - gnome-common
description : |
    A command line based bandwidth monitor.
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
